# Este arquivo define o docker-compose da solução, focando principalmente nos serviços de banco de dados e backend.
# O frontend não está incluído aqui, pois seria implementado de forma nativa no aplicativo.