version: '3.8'

services:
  postgres:
    build:
      context: ./backend/src/app/database
      dockerfile: Dockerfile
    container_name: negociaai-db
    environment:
      POSTGRES_DB: negociaai
      POSTGRES_USER: grupo35
      POSTGRES_PASSWORD: 75N6uHRcrigx7qx9tPCyHmAel1Xa1INg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grupo35 -d negociaai"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - negociaai-net

  backend:
    env_file:
      - ../../.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: negociaai-backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://grupo35:75N6uHRcrigx7qx9tPCyHmAel1Xa1INg@postgres:5432/negociaai
    restart: unless-stopped
    networks:
      - negociaai-net

volumes:
  postgres_data:

networks:
  negociaai-net:
    driver: bridge